org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
flutter.compileSdkVersion=35
flutter.targetSdkVersion=34
flutter.minSdkVersion=21org.gradle.daemon.lockTimeout=60000
org.gradle.cache.timeout=60000
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.java.home=/Users/eslamgamal/Library/Java/JavaVirtualMachines/azul-17.0.14/Contents/Home
#dev.steenbakker.mobile_scanner.useUnbundled=true
